platform :ios, '12.4'

use_frameworks!

inhibit_all_warnings!

target 'app' do
	pod 'ApiAI/Core'
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	pod 'OneSignal'
	pod 'Realm'
	pod 'SinchRTC'

	pod 'CryptoSwift'
	pod 'InputBarAccessoryView'
	pod 'Kingfisher'
	pod 'MBProgressHUD'
	pod 'MGSwipeTableCell'
	pod 'MessageKit'
	pod 'NYTPhotoViewer', '1.2.0'
	pod 'ProgressHUD'
	pod 'Reachability'
	pod 'RNCryptor-objc'
	pod 'SoundManager'
end
